spring:
  profiles:
    active:
      - dog
      - EN
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl
